### PR TITLE
SSM: Second line should say https_proxy

### PR DESCRIPTION
**Pull request by punya**
*Issue #, if available:*

*Description of changes:*

Instead of setting http_proxy twice, we should set http_proxy as well as https_proxy.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by JimbroAmazon** [comment]
Good catch! Thanks so much, Punyashloka.

**Comment by punya** [comment]
@JimbroAmazon thanks for merging the PR. When can we expect to see this reflected on https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-proxy-with-ssm-agent.html? I ask because some of our customers were misled by the old documentation, and I'd love to point them to the fixed version as soon as possible.

**Comment by JimbroAmazon** [comment]
Hi Punyashloka, the updated doc should be live by 4:00 PST today. Thanks!

**Comment by punya** [comment]
@JimbroAmazon just checking in, the doc still doesn't show these changes. When can we expect it to be updated?

**Comment by JimbroAmazon** [comment]
@punya When I view the page here (https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-proxy-with-ssm-agent.html) I see the update. You don't see it on that page?

**Comment by punya** [comment]
My apologies, my browser cache must have been acting up. Please carry on 😄

**Pull request merged**
