### PR TITLE
Add note about AmazonEC2RoleforSSM S3 access

### PR DESCRIPTION
**Pull request by davidfurey**
*Description of changes:*

The AmazonEC2RoleforSSM allows instances to perform more actions that is necessary, this PR documents the minimum set of permissions necessary to use SSM.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by JimbroAmazon** [comment]
Hi David, thanks so much for this pull request. I'm reviewing your changes now.

**Comment by JimbroAmazon** [comment]
Hi David, thanks again for your contribution. I asked our dev lead to review the proposed IAM policy you sent he said that the intent of the policy is great, but the trimmed down version of the policy would actually break some of our features. Explicitly he said: 

Hi Jim,
The proposed content is narrow to the point of breaking features, including inventory upload, compliance reporting, agent update, and others, so I think that calling it the minimum required set of permissions would be confusing for customers who want to use everything that we offer.  If we’re going to publish docs on restricting privileges in IAM (which I think is a good idea overall), we’d get more value from an approach where we provide more info about what each permission is used for so that people can build the role that’s appropriate for them.  That would take some work across our teams, since we don’t already have that content put together.

I'm going to close this PR, and create an action item to create a doc that describes what each permission is used for. Thank you again!

Best wishes,
-Jim

**Comment by davidfurey** [comment]
Great, thanks for reviewing.  It will be really useful to have more detailed docs providing info about what each permission is used for.  More than one team at the Guardian have been quite surprised by how much access the AmazonEC2RoleforSSM grants to instances.

**Comment by davidfurey** [comment]
Until you can produce more detailed docs, it might be worth adding a note to explain that the existing permissions are very open.

**Pull request closed without merging**
