### PR TITLE
Correct version requirement

### PR DESCRIPTION
**Pull request by alanyee**
*Issue #, if available:* N/A

*Description of changes:*
Correct version requirement in docs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tumegan** [comment]
Thank you for your pull request. We've decided not to accept these changes at this time as the documentation is correct as is.

**Comment by alanyee** [comment]
The wording of phrase seems to suggest that it supports Python 2.6.5-2.7.x and just 3.3 rather than Python 2.6.5-2.7.x and 3.3-3.y where x > 3.

**Comment by JimbroAmazon** [comment]
Thanks Alan! I'm going to forward this information to our Session Manager writer and see if he wants to update the docs as you suggested. Apologies for the back and forth on this.

**Comment by tumegan** [comment]
Hi Alan. I just heard back from the service team and they agree with your proposed changes. Thanks for your suggestion!

**Pull request closed without merging**
